.TH PYGYAT 1
.SH NAME
by2py \- Translate pygyat files to python
.SH SYNOPSIS
.B gyat2py
[\fIFLAGS\fR]
.IR scriptfile
.SH DESCRIPTION
.B gyat2py
is an alias for 'pygyat -c'. For more information, look up the manual for pygyat(1).
.SH SEE ALSO
pygyat(1)
.SH AUTHOR
Shamith Pasula 2024
.SH LICENSE
This program is licensed under the MIT license. See [1] for details. TL;DR: Do whatever you want as long as you include the original copyright and license notice.
.TP
[1]
https://github.com/shamith09/pygyat/blob/master/LICENSE



